application: qcmtl
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: front-end/build/css

- url: /js
  static_dir: front-end/build/js

- url: /.*
  script: qcmtl.application

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on
